version: "3.8"

services:
  minify-obfuscator:
    container_name: minify-obfuscator-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data  # Optional: Mount a local folder for persistent storage
    restart: unless-stopped